[package]
name = "claylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shards = { path = "../../shards/rust", features = ["run_bindgen", "dllshard", "scripting"] }
edn-rs = "0.17.0"

[build-dependencies]
cmake = "0.1"
cbindgen = "0.23.0"

[dev-dependencies]
hex = "0.4.3"