name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Checkout Chainblocks
        uses: actions/checkout@v2
        with:
          repository: https://github.com/fragcolor-xyz/chainblocks.git
          ref: devel
          fetch-depth: 1
          submodules: recursive
          path: ../
      - name: Test
        run: |
          cargo test
