name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build libboost-all-dev xorg-dev libdbus-1-dev libssl-dev mesa-utils
          rustup update
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
          path: claymore
      - name: Checkout Chainblocks
        uses: actions/checkout@v2
        with:
          repository: fragcolor-xyz/chainblocks
          ref: devel
          fetch-depth: 1
          submodules: recursive
          path: chainblocks
      - name: Test
        run: |
          cd claymore
          cargo test
